In [5]:
import torch
import torchvision
from torchvision import models
import torchvision.models.efficientnet as e
import torchvision.models.resnet as r
import torch.nn as nn

WEIGHTS = r.resnet50(pretrained= True)

In [6]:
# use GPUs if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [7]:
model = WEIGHTS

In [8]:
WEIGHTS.fc = nn.Linear(2048, 82)

In [10]:
model.load_state_dict(torch.load("./models/xfer-learning-10eps.pkl", map_location=torch.device('cpu'))) # cpu
# model.load_state_dict(torch.load("./models/xfer-learning-10eps.pkl")) # gpu

<All keys matched successfully>

In [11]:
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [12]:
model.to(device)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [13]:
from PIL import Image
from torchvision import transforms

In [14]:
classes = ['adho-mukha-svanasana',
 'adho-mukha-vriksasana',
 'adho-mukha-vrksasana',
 'ananda-balasana',
 'anjaneyasana',
 'ardha-chandrasana',
 'ardha-matsyendrasana',
 'ardha-pincha-mayurasana',
 'ardha-uttanasana',
 'astavakrasana',
 'baddha-konasana',
 'bakasana',
 'balasana',
 'bharadvajasana-i',
 'bhujangasana',
 'bhujapidasana',
 'bitilasana',
 'camatkarasana',
 'chakravakasana',
 'chaturanga-dandasana',
 'dandasana',
 'dhanurasana',
 'dwi-pada-viparita-dandasana',
 'eka-pada-koundinyanasana-i',
 'eka-pada-koundinyanasana-ii',
 'eka-pada-rajakapotasana',
 'eka-pada-rajakapotasana-ii',
 'garudasana',
 'gomukhasana',
 'halasana',
 'kapotasana',
 'makarasana',
 'malasana',
 'marjaryasana',
 'matsyasana',
 'mayurasana',
 'natarajasana',
 'padmasana',
 'paripurna-navasana',
 'parivrtta-trikonasana',
 'parsva-bakasana',
 'pasasana',
 'paschimottanasana',
 'phalakasana',
 'prasarita-padottanasana',
 'purvottanasana',
 'salabhasana',
 'salamba-bhujangasana',
 'salamba-sarvangasana',
 'salamba-sirsasana',
 'savasana',
 'setu-bandha-sarvangasana',
 'sukhasana',
 'supta-baddha-konasana',
 'supta-matsyendrasana',
 'supta-padangusthasana',
 'supta-virasana',
 'tadasana',
 'tittibhasana',
 'tolasana',
 'upavistha-konasana',
 'urdhva-dhanurasana',
 'urdhva-mukha-svanasana',
 'urdhva-prasarita-eka-padasana',
 'ustrasana',
 'utkatasana',
 'uttana-shishosana',
 'uttanasana',
 'utthita-hasta-padangustasana',
 'utthita-hasta-padangusthasana',
 'utthita-parsvakonasana',
 'utthita-trikonasana',
 'vajrasana',
 'vasisthasana',
 'viparita-karani',
 'virabhadrasana-i',
 'virabhadrasana-ii',
 'virabhadrasana-iii',
 'virasana',
 'vriksasana',
 'vrischikasana',
 'vrksasana']

In [19]:
!wget -O utkatasana.jpg https://cdn.yogajournal.com/wp-content/uploads/2021/11/Chair-Pose_Andrew-Clark_2400x1350.jpg

--2023-06-26 02:51:18--  https://cdn.yogajournal.com/wp-content/uploads/2021/11/Chair-Pose_Andrew-Clark_2400x1350.jpg
Resolving cdn.yogajournal.com (cdn.yogajournal.com)... 2620:12a:8001::1, 2620:12a:8000::1, 23.185.0.1
Connecting to cdn.yogajournal.com (cdn.yogajournal.com)|2620:12a:8001::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 122229 (119K) [image/jpeg]
Saving to: ‘utkatasana.jpg’

utkatasana.jpg      100%[===================>] 119.36K   327KB/s    in 0.4s    

2023-06-26 02:51:19 (327 KB/s) - ‘utkatasana.jpg’ saved [122229/122229]



In [20]:
def make_prediction(filepath):
    img = Image.open(filepath)
    transformer = torchvision.transforms.Compose([
        transforms.Resize(size = (224, 224)),
        transforms.ToTensor(),
    ])
    img_normalized = transformer(img).float()
    img_normalized = img_normalized.unsqueeze_(0)
    img_normalized = img_normalized.to(device)
    with torch.no_grad():
        model.eval()
        output = model(img_normalized)
        print(output)
        index = output.data.cpu().numpy().argmax()
        print(index)
        class_name = classes[index]
        print(class_name)
    # model.predict("inference.jpg")

In [21]:
make_prediction("utkatasana.jpg")

tensor([[ 2.0362e+01,  8.7758e+00,  2.5990e+01, -2.9330e+00,  3.2544e+01,
          1.8206e+01,  1.8363e+01,  1.8943e+01,  1.2351e+01, -2.7124e+00,
          1.3963e+01,  8.9649e+00,  7.9687e+00, -2.6835e+00,  1.5603e+01,
         -1.1861e+01,  1.4418e+01,  2.7999e+00,  1.4389e+01,  1.8544e+00,
          2.2805e+01,  7.8263e+00, -5.6727e+00,  2.3732e+01, -1.2077e+00,
          4.0473e+00,  1.7596e+01, -6.5749e+00,  9.2365e+00,  2.4551e-01,
          9.5675e+00,  9.4257e-01,  1.8222e+01,  1.2343e+01,  7.3041e+00,
          4.2306e+00,  1.4498e+01,  2.6587e+01,  2.5676e-03,  1.6729e+01,
          1.0110e+01,  1.2438e+01, -6.7664e-01,  1.3709e+01,  5.0021e+00,
          1.0081e+01,  2.0208e+01,  7.7553e+00,  8.7585e+00,  2.1111e+01,
          6.9942e+00, -1.3129e+01,  1.4525e+00,  1.1531e+01,  1.6870e+01,
          1.9985e+01, -1.5103e+00,  2.1000e+01,  7.9652e+00, -9.2480e+00,
          9.9091e+00,  9.4411e+00,  1.1737e+01,  3.7601e+00,  1.4518e+01,
          4.8273e+01,  9.6724e+00,  2.

In [23]:
!wget -O anjaneyasana.jpg https://www.gaia.com/wp-content/uploads/article-migration-image-1920x1080_TheLungePose-768x432.jpg

--2023-06-26 02:52:20--  https://www.gaia.com/wp-content/uploads/article-migration-image-1920x1080_TheLungePose-768x432.jpg
Resolving www.gaia.com (www.gaia.com)... 2600:9000:20be:ce00:1a:585:f0c0:93a1, 2600:9000:20be:1000:1a:585:f0c0:93a1, 2600:9000:20be:7a00:1a:585:f0c0:93a1, ...
Connecting to www.gaia.com (www.gaia.com)|2600:9000:20be:ce00:1a:585:f0c0:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14771 (14K) [image/jpeg]
Saving to: ‘anjaneyasana.jpg’

anjaneyasana.jpg    100%[===================>]  14.42K  --.-KB/s    in 0s      

2023-06-26 02:52:20 (112 MB/s) - ‘anjaneyasana.jpg’ saved [14771/14771]



In [24]:
make_prediction("anjaneyasana.jpg")

tensor([[ 1.5236e+01,  8.0259e+00,  2.6459e+01, -1.0775e+00,  3.5886e+01,
          2.4685e+01,  1.8597e+01,  1.6425e+01,  1.4232e+01,  4.6247e+00,
          1.7175e+01,  6.5085e+00,  1.0635e+01,  8.7915e+00,  7.5874e+00,
         -7.5887e+00,  9.0901e+00,  7.4321e+00,  8.1009e+00,  3.2302e+00,
          2.6351e+01,  6.1425e+00, -7.9081e+00,  2.4856e+01, -4.5391e+00,
          4.2609e+00,  2.1660e+01,  1.4044e+01,  2.0342e+01, -3.0697e+00,
          3.7611e+00,  2.2480e+00,  1.7758e+01,  6.2440e-03, -3.6745e+00,
         -8.7582e-01,  1.8399e+01,  3.0638e+01,  7.8047e-01,  1.1023e+01,
          1.1027e+01,  6.5704e+00, -4.2489e+00,  6.4812e+00, -7.4802e+00,
          1.2971e+00,  2.0726e+01,  3.4673e+00,  1.5981e+01,  1.5659e+01,
         -4.0335e-01, -1.9818e+01,  8.0764e+00,  7.8856e+00,  1.8976e+01,
          1.1928e+01, -4.4164e+00,  2.8538e+01,  6.5533e+00,  9.2675e-01,
          4.2739e+00,  2.0787e+00,  1.1945e+01,  1.0361e+01,  7.4317e+00,
          4.9208e+01,  1.2048e+01,  8.

In [25]:
!wget -O tittibhasana.jpg https://www.fitsri.com/wp-content/uploads/2020/10/firefly-pose-tittibhasana.jpg

--2023-06-26 02:52:31--  https://www.fitsri.com/wp-content/uploads/2020/10/firefly-pose-tittibhasana.jpg
Resolving www.fitsri.com (www.fitsri.com)... 2606:4700:3032::6815:2495, 2606:4700:3036::ac43:c31f, 104.21.36.149, ...
Connecting to www.fitsri.com (www.fitsri.com)|2606:4700:3032::6815:2495|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49481 (48K) [image/jpeg]
Saving to: ‘tittibhasana.jpg’

tittibhasana.jpg    100%[===================>]  48.32K  --.-KB/s    in 0.02s   

2023-06-26 02:52:33 (2.13 MB/s) - ‘tittibhasana.jpg’ saved [49481/49481]



In [26]:
make_prediction("tittibhasana.jpg")

tensor([[ 8.2112e+00,  8.7616e+00,  1.5270e+01, -6.1950e-01,  1.9923e+01,
          6.2621e+00,  9.0548e+00,  1.4827e+01,  2.4554e+01,  3.2438e+01,
          6.1196e-01,  2.1270e+01,  1.9677e+01, -9.8215e+00, -9.2576e-03,
          2.5986e+01,  1.1885e+01, -1.2349e+00,  2.8453e+00,  1.6129e+00,
          2.2684e+01,  1.8447e+01, -1.1348e+01,  2.6245e+01,  2.0871e-01,
          1.2638e+01,  2.7487e+01,  1.7719e+01,  6.8021e-01,  8.6236e+00,
          1.0883e+01, -1.9406e+00,  2.6463e+01,  1.6720e+01,  4.5426e+00,
          3.1014e+00,  1.8195e+01,  1.4181e+01,  3.6028e+00,  1.7946e+01,
          3.1038e+01,  8.4566e+00,  8.2092e+00,  1.6080e+01,  6.5669e+00,
          4.2980e+00,  2.8039e+01,  5.3482e+00, -1.2073e+00,  1.6287e+01,
         -3.2971e+00, -7.9597e+00,  2.8037e+00,  7.3924e+00,  1.6023e+01,
          1.0417e+01,  1.3744e+01,  1.8815e+01,  2.3062e+01, -3.4037e+00,
          1.3689e+01,  8.0551e+00,  4.6605e+00,  2.8781e+00,  6.9166e+00,
          2.6657e+01,  1.1837e+01,  2.